### ISSUE TITLE
Is your plan plagiarized or merely a repetition of what has been presented in existing literature?

### ISSUE THREAD

**Issue by wangzhenlin123** [OpenImagingLab/AdaptiveISP#1]
Why didn't you reference the previously existing similar ideas?  

https://zhuanlan.zhihu.com/p/447678747
[1].Image-Adaptive YOLO for Object Detection in Adverse Weather Conditions
![image](https://github.com/user-attachments/assets/cb6fa628-4fac-4ce0-a58f-0138002d7ec5)

**Comment by iimmortall** [comment]
The goals of these two works are fundamentally different!!!!!!! The work you mentioned focuses solely on predicting ISP parameters using a network predictor, and we have already cited similar methods in our paper. In contrast, our work aims to identify the most suitable ISP pipeline for downstream computer vision tasks, while simultaneously constraining resource consumption. We kindly ask that you read the original paper carefully!!!!!

**Comment by iimmortall** [comment]
Since no response has been received for over two weeks, I will be closing this issue. If you have any questions or need further discussion, feel free to reopen this issue or create a new one. Thank you for your understanding and cooperation.
