### ISSUE TITLE
about LOD dataset

### ISSUE THREAD

**Issue by MEYE66** [OpenImagingLab/AdaptiveISP#2]
hello, this is an exciting idea.
When I tried to unzip the provided LoD dataset, I got an archive error, and the official LoD dataset does not provide a train/val.txt file.
I don't know if the compressed file is correct. Can you check it?

**Comment by shani-sony** [comment]
@MEYE66 Hi! Did you manage to solve it? I have the same issue.

**Comment by MEYE66** [comment]
I contacted the first author and he sent me a segmentation dataset. I don't know if it is publicly available.
